# -*- coding: utf-8 -*-

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(480, 320)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 165, 79);")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setProperty("FramelessWindowHint", True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelCam01 = QtWidgets.QLabel(self.centralwidget)
        self.LabelCam01.setGeometry(QtCore.QRect(180, 100, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.LabelCam01.setFont(font)
        self.LabelCam01.setStyleSheet("background-color: rgb(10, 54, 94);")
        self.LabelCam01.setObjectName("LabelCam01")
        self.labelIP = QtWidgets.QLabel(self.centralwidget)
        self.labelIP.setGeometry(QtCore.QRect(240, 20, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.labelIP.setFont(font)
        self.labelIP.setObjectName("labelIP")
        self.LabelStatusCam01 = QtWidgets.QLabel(self.centralwidget)
        self.LabelStatusCam01.setGeometry(QtCore.QRect(270, 150, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.LabelStatusCam01.setFont(font)
        self.LabelStatusCam01.setStyleSheet("background-color: rgb(10, 54, 94);")
        self.LabelStatusCam01.setObjectName("LabelStatusCam01")
        self.labelIPAddress = QtWidgets.QLabel(self.centralwidget)
        self.labelIPAddress.setGeometry(QtCore.QRect(270, 20, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.labelIPAddress.setFont(font)
        self.labelIPAddress.setObjectName("labelIPAddress")
        self.LabelStatusPLC01 = QtWidgets.QLabel(self.centralwidget)
        self.LabelStatusPLC01.setGeometry(QtCore.QRect(240, 190, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.LabelStatusPLC01.setFont(font)
        self.LabelStatusPLC01.setStyleSheet("background-color: rgb(10, 54, 94);")
        self.LabelStatusPLC01.setObjectName("LabelStatusPLC01")
        self.ButtonRestart = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonRestart.setGeometry(QtCore.QRect(20, 110, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Bold)
        font.setKerning(True)
        self.ButtonRestart.setFont(font)
        self.ButtonRestart.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(0, 0, 0);")
        self.ButtonRestart.setObjectName("ButtonRestart")
        self.ButtonShutdown = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonShutdown.setGeometry(QtCore.QRect(20, 170, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Bold)
        font.setKerning(True)
        self.ButtonShutdown.setFont(font)
        self.ButtonShutdown.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(0, 0, 0);")
        self.ButtonShutdown.setObjectName("ButtonShutdown")
        self.LabelStatusCam01_2 = QtWidgets.QLabel(self.centralwidget)
        self.LabelStatusCam01_2.setGeometry(QtCore.QRect(180, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.LabelStatusCam01_2.setFont(font)
        self.LabelStatusCam01_2.setStyleSheet("background-color: rgb(10, 54, 94);")
        self.LabelStatusCam01_2.setObjectName("LabelStatusCam01_2")
        self.LabelStatusCam01_3 = QtWidgets.QLabel(self.centralwidget)
        self.LabelStatusCam01_3.setGeometry(QtCore.QRect(180, 190, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.LabelStatusCam01_3.setFont(font)
        self.LabelStatusCam01_3.setStyleSheet("background-color: rgb(10, 54, 94);")
        self.LabelStatusCam01_3.setObjectName("LabelStatusCam01_3")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(10, 10, 211, 51))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("/home/conecsa/color-detect/color-detect-back/Logo.png"))
        self.Logo.setObjectName("Logo")
        self.labelIPAddress_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelIPAddress_2.setGeometry(QtCore.QRect(60, 40, 191, 21))
        font = QtGui.QFont()
        font.setFamily("ISOCP_IV50")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Bold)
        font.setKerning(True)
        self.labelIPAddress_2.setFont(font)
        self.labelIPAddress_2.setObjectName("labelIPAddress_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 80, 461, 161))
        self.label.setStyleSheet("background-color: rgb(10, 54, 94);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 461, 61))
        self.label_2.setStyleSheet("background-color: rgb(10, 54, 94);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.LabelCam01_2 = QtWidgets.QLabel(self.centralwidget)
        self.LabelCam01_2.setGeometry(QtCore.QRect(20, 270, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.LabelCam01_2.setFont(font)
        self.LabelCam01_2.setStyleSheet("background-color: rgb(10, 54, 94);")
        self.LabelCam01_2.setObjectName("LabelCam01_2")
        self.label.raise_()
        self.LabelCam01.raise_()
        self.labelIP.raise_()
        self.LabelStatusCam01.raise_()
        self.labelIPAddress.raise_()
        self.LabelStatusPLC01.raise_()
        self.ButtonRestart.raise_()
        self.ButtonShutdown.raise_()
        self.LabelStatusCam01_2.raise_()
        self.LabelStatusCam01_3.raise_()
        self.Logo.raise_()
        self.labelIPAddress_2.raise_()
        self.label_2.raise_()
        self.LabelCam01_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ConColorDetect v1.0"))
        self.LabelCam01.setText(_translate("MainWindow", "Câmera: cam01"))
        self.labelIP.setText(_translate("MainWindow", "IP:"))
        self.LabelStatusCam01.setText(_translate("MainWindow", "Status cam01"))
        self.labelIPAddress.setText(_translate("MainWindow", "Endereço IP"))
        self.LabelStatusPLC01.setText(_translate("MainWindow", "Status PLC"))
        self.ButtonRestart.setText(_translate("MainWindow", "Restart"))
        self.ButtonShutdown.setText(_translate("MainWindow", "Shutdown"))
        self.LabelStatusCam01_2.setText(_translate("MainWindow", "Câmera:"))
        self.LabelStatusCam01_3.setText(_translate("MainWindow", "PLC:"))
        self.labelIPAddress_2.setText(_translate("MainWindow", "Color Detect v1.0"))
        self.LabelCam01_2.setText(_translate("MainWindow", "Conecsa Automação - 2022"))
